// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"database/sql"
	"time"
)

type ReviseItem struct {
	ID             string
	UserID         string
	Name           string
	Description    sql.NullString
	Tags           sql.NullString
	CreatedAt      time.Time
	UpdatedAt      time.Time
	DeletedAt      sql.NullTime
	LastRivisedAt  time.Time
	NextRevisionAt time.Time
}

type Revision struct {
	ID           string
	ReviseItemID string
	RevisedAd    time.Time
}

type User struct {
	ID           string
	ChatID       int64
	CreatedAt    time.Time
	UpdatedAt    time.Time
	Language     sql.NullString
	ReminderTime string
}
