// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"database/sql"
	"time"
)

type ReviseItem struct {
	ID             string
	UserID         string
	Name           string
	Description    sql.NullString
	Tags           sql.NullString
	CreatedAt      sql.NullTime
	UpdatedAt      sql.NullTime
	DeletedAt      sql.NullTime
	LastRivisedAt  sql.NullTime
	NextRevisionAt sql.NullTime
}

type Revision struct {
	ID           string
	ReviseItemID string
	RevisedAd    time.Time
}

type User struct {
	ID     string
	ChatID int64
}
