// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: user.sql

package sqlc

import (
	"context"
)

const saveUser = `-- name: SaveUser :exec
INSERT INTO users (
    id, chat_id 
) VALUES ( ?, ? )
`

type SaveUserParams struct {
	ID     string
	ChatID int64
}

func (q *Queries) SaveUser(ctx context.Context, arg SaveUserParams) error {
	_, err := q.db.ExecContext(ctx, saveUser, arg.ID, arg.ChatID)
	return err
}
